### ISSUE TITLE
response_type as query param?

### ISSUE THREAD

**Issue by tb582** [RIPAGlobal/omniauth-azure-activedirectory-v2#15]
Looking here: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#code-try-1

it seems like response_type is required yet its not specifically part of the README table - I assume we are to use authorize_params for this?

**Comment by whithajess** [comment]
@tb582 Are you having some kind of actual issue?

This gem works using its dependencies, specifically `omniauth-oauth2` and transiently `oauth2` and `omniauth` - I think you will find `response_type` defined in `oauth2` based on `strategy`
