### ISSUE TITLE
No Refresh Token

### ISSUE THREAD

**Issue by Gambitboy** [RIPAGlobal/omniauth-azure-activedirectory-v2#4]
Hi, after authenticating and getting the credential information, my payload does not have a refresh_token.
Any idea why this could be?
I've been trying to see if it's an application configuration on azure but doesn't seem that way.

**Comment by Gambitboy** [comment]
So I figured it out.

Azure issues a refresh_token when you authenticate with the scope 'offline_access'

To do this, I passed a custom scope alongside my name, client_id, client_secret and strategy_class variables

`scope: 'openid profile email offline_access'`

**Comment by pond** [comment]
Thanks for following up with the solution `:-)`

**Comment by SebAshton** [comment]
@Gambitboy thank you
