### ISSUE TITLE
Authentication failure on rails api

### ISSUE THREAD

**Issue by inska** [RIPAGlobal/omniauth-azure-activedirectory-v2#5]
Dear,

Could you please give me a some clue that can't authenticate because of InvalidAuthenticityToken problem?

Rails: 6.0.0 (installed api only mode)
ominiauth-azure-activedirecotry-v2 : 1.0.0

I'm following [the article](https://medium.com/committed-engineers/setup-azure-ad-oauth-2-0-with-ruby-on-rails-and-devise-39848e3ed532), but I got below issue:

E, [2022-04-13T13:10:55.623352 #24682] ERROR -- omniauth: (azure_activedirectory_v2) Authentication failure! ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken, ActionController::InvalidAuthenticityToken

So I tried to `skip_before_action :verify_authenticity_token`, but there's another issue that rails-api don't have this method by default.

In this case, how can I fix and go ahead?

Best,

**Comment by inska** [comment]
It was correct - after I changed from ActionController::API to ActionController::Base on application_controller.rb, everything works well.

```
class ApplicationController < ActionController::Base
```

**Comment by pond** [comment]
Glad you got it sorted.

It doesn't make sense to try and use Azure AD on an API-only application since the user _must_ have a front-end UI to interact with in order to be able to use the Azure AD

**Comment by pond** [comment]
Glad you got it sorted :-)
